# action.yml
name: 'GH-Pages-Deploy'
description: 'Build docker container and build package'
inputs:
  github-token:
    description: 'Github token for push'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}