#!/usr/bin/env node

/**
 * @author Andreas Karner <andreas.karner@student.tugraz.at>
 * @description generate crowdin message file based on msg/*.json files, please run first create_msg_json.js if needed
 *  
 * @changelog 2019-08-14: initial version
 *            2019-08-23: added some more comments, refactor code
 *            2019-09-06: changed logic to generate just one catblocks_msgs.js file
 */

const fs = require('fs');
const path = require('path');

// please define config here
const MSG_DIR = path.join('msg');
const JSON_DIR = path.join(MSG_DIR, 'json');
const MESSAGE_FILE = path.join(MSG_DIR, 'catblocks_msgs.js');

const MESSAGE_HEADER = `// This file was automatically generated by ${path.basename(__filename)}
// Please do not modify.

'use strict';

goog.provide('Blockly.CatblocksMsgs.allLocales');
goog.require('Blockly.CatblocksMsgs');
`;

// generate main catblocks_msgs.js file
const message_fd = fs.openSync(MESSAGE_FILE, 'w');
fs.writeSync(message_fd, MESSAGE_HEADER);

// generate for each msg/*.json file a object in catblocks_msgs.js files
const langfiles = fs.readdirSync(JSON_DIR, { encoding: 'utf-8' });
langfiles.forEach(langfile => {
  if (langfile.match(/.+\.json$/)) {
    const lang_name = langfile.substr(0, langfile.indexOf('.'))
    const json_path = path.join(JSON_DIR, langfile);
    const json_object = JSON.parse(fs.readFileSync(json_path, { encoding: 'utf-8' }));

    fs.writeSync(message_fd, `\n\nBlockly.CatblocksMsgs.locales["${lang_name}"] = {\n`)
    Object.keys(json_object).forEach(key => {
      fs.writeSync(message_fd, `  "${key}": "${json_object[key]}",\n`);
    });

    fs.writeSync(message_fd, `}`);
  }
});

fs.closeSync(message_fd);