# action.yml
name: 'Jest-Docker-Runer'
description: 'Build docker container and execute jest tests'
inputs:
  github-token:
    description: 'Github token for report push'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
