// This file was automatically generated by create_msg.js
// Please do not modify.
/* eslint no-useless-escape: 0 */
import Blockly from "blockly";
import $ from "jquery";

Blockly.CatblocksMsgs = {};
Blockly.CatblocksMsgs.locales = {};

Blockly.CatblocksMsgs.currentLocale_ = 'en';

Blockly.CatblocksMsgs.hasLocale = function(locale) {
  return Object.keys(Blockly.CatblocksMsgs.locales).includes(locale);
};

Blockly.CatblocksMsgs.setLocale = function(locale, filesLocation = undefined) {
  if (Blockly.CatblocksMsgs.hasLocale(locale)) {
    if (Object.keys(Blockly.CatblocksMsgs.locales[locale]).length === 1) {
      return Blockly.CatblocksMsgs.loadNewLocale(locale, filesLocation).then(() => {
        Blockly.CatblocksMsgs.currentLocale_ = locale;
        Blockly.Msg = Object.assign({}, Blockly.Msg, Blockly.CatblocksMsgs.locales[locale]);
      });
    } else {
      Blockly.CatblocksMsgs.currentLocale_ = locale;
      Blockly.Msg = Object.assign({}, Blockly.Msg, Blockly.CatblocksMsgs.locales[locale]);
      return Promise.resolve();
    }
  } else {
    console.warn('Fallback to default language and ignoring unrecognized locale: ' + locale);
    return Blockly.CatblocksMsgs.setLocale(Blockly.CatblocksMsgs.currentLocale_);
  }
};

Blockly.CatblocksMsgs.reloadCurrentLocale = function() {
  return Blockly.CatblocksMsgs.setLocale(Blockly.CatblocksMsgs.currentLocale_);
};

Blockly.CatblocksMsgs.getCurrentLocale = function() {
  return Blockly.CatblocksMsgs.currentLocale_;
};

Blockly.CatblocksMsgs.getCurrentLocaleValues = function() {
  return Blockly.CatblocksMsgs.locales[Blockly.CatblocksMsgs.getCurrentLocale()];
};

Blockly.CatblocksMsgs.loadNewLocale = function(locale, filesLocation) {
  let json_object = [];
  let url = window.location.protocol + "//" + window.location.host + "/i18n/" + locale + ".json";

  if (filesLocation != null) {
    if (filesLocation.startsWith("http")) {
      url = filesLocation.replace(/\/$/, "");
      url += "/" + locale + ".json";

    } else {
      url = filesLocation.replace(/\/$/, "") + "/" + locale + ".json";
      url = url.replace(/^\//, "");
      url = window.location.protocol + "//" + window.location.host + "/" + url;
    }
  }

  return $.getJSON(url, function (result) {
    json_object = result;
    Object.keys(json_object).forEach(key => {
      if (key !== "DROPDOWN_NAME")
        Blockly.CatblocksMsgs.locales[locale][key] = json_object[key];
    });
  });
};

Blockly.CatblocksMsgs.locales = {
  "af": { "DROPDOWN_NAME": "Afrikaans" },
  "ar": { "DROPDOWN_NAME": "Arabic" },
  "az": { "DROPDOWN_NAME": "Azeri (Latin)" },
  "bg": { "DROPDOWN_NAME": "Bulgarian" },
  "bn": { "DROPDOWN_NAME": "bn" },
  "bs": { "DROPDOWN_NAME": "bs" },
  "ca": { "DROPDOWN_NAME": "Catalan" },
  "cs": { "DROPDOWN_NAME": "Czech" },
  "da": { "DROPDOWN_NAME": "Danish" },
  "de": { "DROPDOWN_NAME": "German" },
  "el": { "DROPDOWN_NAME": "Greek" },
  "en": { "DROPDOWN_NAME": "English" },
  "en_AU": { "DROPDOWN_NAME": "English (Australia)" },
  "en_CA": { "DROPDOWN_NAME": "English (Canada)" },
  "en_GB": { "DROPDOWN_NAME": "English (United Kingdom)" },
  "es": { "DROPDOWN_NAME": "Spanish" },
  "fa": { "DROPDOWN_NAME": "Farsi" },
  "fi": { "DROPDOWN_NAME": "Finnish" },
  "fr": { "DROPDOWN_NAME": "French" },
  "gl": { "DROPDOWN_NAME": "Galician" },
  "gu": { "DROPDOWN_NAME": "Gujarati" },
  "ha": { "DROPDOWN_NAME": "ha" },
  "hi": { "DROPDOWN_NAME": "Hindi" },
  "hr": { "DROPDOWN_NAME": "Croatian" },
  "hu": { "DROPDOWN_NAME": "Hungarian" },
  "ig": { "DROPDOWN_NAME": "ig" },
  "in": { "DROPDOWN_NAME": "in" },
  "it": { "DROPDOWN_NAME": "Italian" },
  "iw": { "DROPDOWN_NAME": "iw" },
  "ja": { "DROPDOWN_NAME": "Japanese" },
  "kk": { "DROPDOWN_NAME": "Kazakh" },
  "kn": { "DROPDOWN_NAME": "Kannada" },
  "ko": { "DROPDOWN_NAME": "Korean" },
  "lt": { "DROPDOWN_NAME": "Lithuanian" },
  "mk": { "DROPDOWN_NAME": "FYRO Macedonian" },
  "ml": { "DROPDOWN_NAME": "ml" },
  "ms": { "DROPDOWN_NAME": "Malay" },
  "nl": { "DROPDOWN_NAME": "Dutch" },
  "no": { "DROPDOWN_NAME": "no" },
  "pl": { "DROPDOWN_NAME": "Polish" },
  "ps": { "DROPDOWN_NAME": "Pashto" },
  "pt": { "DROPDOWN_NAME": "Portuguese" },
  "pt_BR": { "DROPDOWN_NAME": "Portuguese (Brazil)" },
  "ro": { "DROPDOWN_NAME": "Romanian" },
  "ru": { "DROPDOWN_NAME": "Russian" },
  "sd": { "DROPDOWN_NAME": "sd" },
  "si": { "DROPDOWN_NAME": "si" },
  "sk": { "DROPDOWN_NAME": "Slovak" },
  "sl": { "DROPDOWN_NAME": "Slovenian" },
  "sq": { "DROPDOWN_NAME": "Albanian" },
  "sr": { "DROPDOWN_NAME": "sr" },
  "sr_CS": { "DROPDOWN_NAME": "Serbian (Latin)" },
  "sr_SP": { "DROPDOWN_NAME": "Serbian (Cyrillic) (Serbia and Montenegro)" },
  "sv": { "DROPDOWN_NAME": "Swedish" },
  "sw": { "DROPDOWN_NAME": "Swahili" },
  "ta": { "DROPDOWN_NAME": "Tamil" },
  "te": { "DROPDOWN_NAME": "Telugu" },
  "th": { "DROPDOWN_NAME": "Thai" },
  "tr": { "DROPDOWN_NAME": "Turkish" },
  "tw": { "DROPDOWN_NAME": "tw" },
  "uk": { "DROPDOWN_NAME": "Ukrainian" },
  "ur": { "DROPDOWN_NAME": "Urdu" },
  "vi": { "DROPDOWN_NAME": "Vietnamese" },
  "zh_CN": { "DROPDOWN_NAME": "Chinese (S)" },
  "zh_TW": { "DROPDOWN_NAME": "Chinese (T)" },
};