name: "Catroid Support Checker Action"
description: "Compares Catroid and Catblocks properties (supported blocks and language version) and sends a report to Slack"
inputs:
    slack_webhook:
      description: 'Webhook to post on in #catblocks Slack channel'
      required: true
runs:
    using: 'docker'
    image: 'Dockerfile'
    args: 
        - ${{ inputs.slack_webhook }}

if: steps.git-check.outputs.modified == 'true'
run:  |
    git config --global user.name 'Gregor Potthast'
    git config --global user.email 'potthast@student.tugraz.at'
    git add -A
    git commit -m 'Automatically fetch language updates'
    git push