name: "Catroid Support Checker Action"
description: "Compares Catroid and Catblocks properties (supported blocks and language version) and sends a report to Slack"
inputs:
    slack_webhook:
      description: 'Webhook to post on in #catblocks Slack channel'
      required: true
runs:
    using: 'docker'
    image: 'Dockerfile'
    args: 
        - ${{ inputs.slack_webhook }}
with:
    add: '.'
    message: 'Automatically fetch Language Updates from Catroid'
    branch_mode: 'Language-Updates'

on:
    push:
        branches:
            - Language-Updates
    pull_request:
        branches:
            - Language-Updates
        base:
            - develop