pipeline {
    agent {
        docker {
            image 'catblocks:v1' 
            args '-p 3000:3000' 
        }
    }
    stages {
        stage('Build') { 
            steps {
                sh 'cd ./scratch-blocks-develop/ && npm install'
            }
        }
        stage ('Test') {
            steps {
                sh 'cd ./scratch-blocks-develop/ && npm test'
                junit './scratch-blocks-develop/jest-juint-result.xml'
            }
        }
    }
}
