pipeline {
    agent {
        docker {
            image 'catblocks:v1' 
            args '-p 3000:3000' 
        }
    }
    stages {
        stage('Build') { 
            steps {
                sh 'cd ./scratch-blocks-develop/ && npm install'
            }
        }
        stage ('Tests') {
        withEnv(["JEST_JUNIT_OUTPUT=./jest-test-results.xml"]) {
            sh 'cd ./scratch-blocks-develop/ && npm test -- --ci --testResultsProcessor="jest-junit"'
        }
        junit 'jest-test-results.xml'
        }
    }
}
