// This file was automatically generated by create_messages.js
// Please do not modify.

'use strict';

goog.provide('Blockly.ScratchMsgs.allLocales');
goog.require('Blockly.ScratchMsgs');

import de_rDE from './js/de_rDE.js'
Blockly.ScratchMsgs.locales["de_rDE"] = de_rDE;
import en_rAU from './js/en_rAU.js'
Blockly.ScratchMsgs.locales["en_rAU"] = en_rAU;
import en_rCA from './js/en_rCA.js'
Blockly.ScratchMsgs.locales["en_rCA"] = en_rCA;
import en_rGB from './js/en_rGB.js'
Blockly.ScratchMsgs.locales["en_rGB"] = en_rGB;
import es_rES from './js/es_rES.js'
Blockly.ScratchMsgs.locales["es_rES"] = es_rES;
import fa_rAF from './js/fa_rAF.js'
Blockly.ScratchMsgs.locales["fa_rAF"] = fa_rAF;
import fa_rIR from './js/fa_rIR.js'
Blockly.ScratchMsgs.locales["fa_rIR"] = fa_rIR;
import fi_rFI from './js/fi_rFI.js'
Blockly.ScratchMsgs.locales["fi_rFI"] = fi_rFI;
import fr_rFR from './js/fr_rFR.js'
Blockly.ScratchMsgs.locales["fr_rFR"] = fr_rFR;
import gl_rES from './js/gl_rES.js'
Blockly.ScratchMsgs.locales["gl_rES"] = gl_rES;
import gu_rIN from './js/gu_rIN.js'
Blockly.ScratchMsgs.locales["gu_rIN"] = gu_rIN;
import ha_rHG from './js/ha_rHG.js'
Blockly.ScratchMsgs.locales["ha_rHG"] = ha_rHG;
import hi_rIN from './js/hi_rIN.js'
Blockly.ScratchMsgs.locales["hi_rIN"] = hi_rIN;
import hr_rHR from './js/hr_rHR.js'
Blockly.ScratchMsgs.locales["hr_rHR"] = hr_rHR;
import hu_rHU from './js/hu_rHU.js'
Blockly.ScratchMsgs.locales["hu_rHU"] = hu_rHU;
import ig_rNG from './js/ig_rNG.js'
Blockly.ScratchMsgs.locales["ig_rNG"] = ig_rNG;
import in_rID from './js/in_rID.js'
Blockly.ScratchMsgs.locales["in_rID"] = in_rID;
import it_rIT from './js/it_rIT.js'
Blockly.ScratchMsgs.locales["it_rIT"] = it_rIT;
import iw_rIL from './js/iw_rIL.js'
Blockly.ScratchMsgs.locales["iw_rIL"] = iw_rIL;
import ja_rJP from './js/ja_rJP.js'
Blockly.ScratchMsgs.locales["ja_rJP"] = ja_rJP;
import kk_rKZ from './js/kk_rKZ.js'
Blockly.ScratchMsgs.locales["kk_rKZ"] = kk_rKZ;
import kn_rIN from './js/kn_rIN.js'
Blockly.ScratchMsgs.locales["kn_rIN"] = kn_rIN;
import ko_rKR from './js/ko_rKR.js'
Blockly.ScratchMsgs.locales["ko_rKR"] = ko_rKR;
import lt_rLT from './js/lt_rLT.js'
Blockly.ScratchMsgs.locales["lt_rLT"] = lt_rLT;
import mk_rMK from './js/mk_rMK.js'
Blockly.ScratchMsgs.locales["mk_rMK"] = mk_rMK;
import ml_rIN from './js/ml_rIN.js'
Blockly.ScratchMsgs.locales["ml_rIN"] = ml_rIN;
import ms_rMY from './js/ms_rMY.js'
Blockly.ScratchMsgs.locales["ms_rMY"] = ms_rMY;
import nl_rNL from './js/nl_rNL.js'
Blockly.ScratchMsgs.locales["nl_rNL"] = nl_rNL;
import no_rNO from './js/no_rNO.js'
Blockly.ScratchMsgs.locales["no_rNO"] = no_rNO;
import pl_rPL from './js/pl_rPL.js'
Blockly.ScratchMsgs.locales["pl_rPL"] = pl_rPL;
import ps_rAF from './js/ps_rAF.js'
Blockly.ScratchMsgs.locales["ps_rAF"] = ps_rAF;
import pt_rBR from './js/pt_rBR.js'
Blockly.ScratchMsgs.locales["pt_rBR"] = pt_rBR;
import pt_rPT from './js/pt_rPT.js'
Blockly.ScratchMsgs.locales["pt_rPT"] = pt_rPT;
import ro_rRO from './js/ro_rRO.js'
Blockly.ScratchMsgs.locales["ro_rRO"] = ro_rRO;
import ru_rRU from './js/ru_rRU.js'
Blockly.ScratchMsgs.locales["ru_rRU"] = ru_rRU;
import sd_rPK from './js/sd_rPK.js'
Blockly.ScratchMsgs.locales["sd_rPK"] = sd_rPK;
import si_rLK from './js/si_rLK.js'
Blockly.ScratchMsgs.locales["si_rLK"] = si_rLK;
import sk_rSK from './js/sk_rSK.js'
Blockly.ScratchMsgs.locales["sk_rSK"] = sk_rSK;
import sl_rSI from './js/sl_rSI.js'
Blockly.ScratchMsgs.locales["sl_rSI"] = sl_rSI;
import sq_rAL from './js/sq_rAL.js'
Blockly.ScratchMsgs.locales["sq_rAL"] = sq_rAL;
import sr_rCS from './js/sr_rCS.js'
Blockly.ScratchMsgs.locales["sr_rCS"] = sr_rCS;
import sr_rSP from './js/sr_rSP.js'
Blockly.ScratchMsgs.locales["sr_rSP"] = sr_rSP;
import sv_rSE from './js/sv_rSE.js'
Blockly.ScratchMsgs.locales["sv_rSE"] = sv_rSE;
import sw_rKE from './js/sw_rKE.js'
Blockly.ScratchMsgs.locales["sw_rKE"] = sw_rKE;
import ta_rIN from './js/ta_rIN.js'
Blockly.ScratchMsgs.locales["ta_rIN"] = ta_rIN;
import te_rIN from './js/te_rIN.js'
Blockly.ScratchMsgs.locales["te_rIN"] = te_rIN;
import th_rTH from './js/th_rTH.js'
Blockly.ScratchMsgs.locales["th_rTH"] = th_rTH;
import tr_rTR from './js/tr_rTR.js'
Blockly.ScratchMsgs.locales["tr_rTR"] = tr_rTR;
import tw_rTW from './js/tw_rTW.js'
Blockly.ScratchMsgs.locales["tw_rTW"] = tw_rTW;
import uk_rUA from './js/uk_rUA.js'
Blockly.ScratchMsgs.locales["uk_rUA"] = uk_rUA;
import ur_rPK from './js/ur_rPK.js'
Blockly.ScratchMsgs.locales["ur_rPK"] = ur_rPK;
import vi_rVN from './js/vi_rVN.js'
Blockly.ScratchMsgs.locales["vi_rVN"] = vi_rVN;
import zh_rCN from './js/zh_rCN.js'
Blockly.ScratchMsgs.locales["zh_rCN"] = zh_rCN;
import zh_rTW from './js/zh_rTW.js'
Blockly.ScratchMsgs.locales["zh_rTW"] = zh_rTW;
