name: Deploy develop page to gh-pages

on:
  push:
    branches: [ develop ] # merge creates commit + push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Project and push to gh-pages
      uses: ./gh-pages-deploy-action/