name: Deploy develop page to gh-pages

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Project
      uses: ./gh-pages-deploy-action/
