name: Catblocks Pull Request Action

on: 
  pull_request:
    types: [opened, reopened]

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: Catrobat/Catblocks
          ref: BLOCKS-57
      - name: Run jest in docker
        uses: ./jest-testing-action/
        id: jestTest
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout test report branch
        if: always()
        uses: actions/checkout@v2
        with:
          repository: Catrobat/Catblocks
          ref: gh-pages
          path: gh-pages-branch
      - name: Prepare test report
        if: always()
        run: cd ./gh-pages-branch/ && mkdir -p ./testReport/ && cp ./reports/rep_*${GITHUB_SHA}*.html testReport/
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: ReportCatblocks
          path: ./gh-pages-branch/testReport/
      
  uploadDocker:
    runs-on: ubuntu-latest
    name: Create new artifact for PO review
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare artifact entrypoint.sh file
        run: cd ./docker/po-review && sed -i "s/{{COMMIT}}/${GITHUB_SHA}/g" entrypoint.sh && sed -i "s/{{BRANCH}}/${GITHUB_REF##*/}/g" entrypoint.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: DockerCatblocks
          path: ./docker/po-review/
