name: Catblocks Test Runner

on: [push]

jobs:
  # testing:
  # runs-on: ubuntu-latest
  # name: Build catblocks container and run jest tests
  # steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #   - name: Jest, running test suites
  #     uses: ./jest-testing-action/ # Use local repository action
  #     id: jestTest
  #     with:
  #       github-token: ${{ secrets.GITHUB_TOKEN }}
  public:
    #     needs: [testing]
    runs-on: ubuntu-latest
    name: Create new artifact for PO review
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare artifact entrypoint.sh file
        run: env && cd ./docker/po-review && sed -i "s/{{COMMIT}}/${GITHUB_SHA}/g" entrypoint.sh && sed -i "s/{{BRANCH}}/${GITHUB_REF##*/}/g" entrypoint.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: DockerContainer
          path: ./docker/po-review/
