name: Merge Action

on:
  push:
    branches: [ develop ] # merge creates commit + push

jobs:
  deployTestingpage:
    name: Deploy Testpage to GH-Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Project and push to gh-pages
      uses: ./gh-pages-deploy-action/