name: Pull Request Action

on: 
  pull_request:
    types: [opened, reopened, labeled, synchronize]
    # labeled: when adding a label to PR
    # synchronize: when adding new commit after PR is already opened

jobs:
  runTests:
    if: github.repository == 'Catrobat/Catblocks'
    name: Run Auto-Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run jest test action
        uses: ./github_actions/jest-testing-action/
      - name: Prepare test report
        if: always()
        run: cd /home/runner/work/Catblocks/Catblocks && mkdir -p ./catblocksTestReport/ && cp ./jest_html_reporters.html ./catblocksTestReport/rep_${GITHUB_SHA}.html
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: CatblocksTestReport
          path: /home/runner/work/Catblocks/Catblocks/catblocksTestReport/
      
  uploadDocker:
    if: github.repository == 'Catrobat/Catblocks'
    name: Create new artifact for PO review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare artifact entrypoint.sh file
        run: cd ./docker/po-review && sed -i "s/{{COMMIT}}/${GITHUB_SHA}/g" entrypoint.sh && sed -i "s/{{BRANCH}}/${GITHUB_REF##*/}/g" entrypoint.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: DockerCatblocks
          path: ./docker/po-review/


  lintCode:
    if: github.repository == 'Catrobat/Catblocks'
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Yarn
        run: npm install -g yarn
      - run: yarn install
      - run: yarn lint
      - name: Uninstall Yarn
        if: always()
        run: npm uninstall -g yarn
