name: Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: install # will run `yarn install` command
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: clean # will run `yarn clean` command
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: render:build # will run `yarn render:build` command
